version: "3"

services:
  influxdb:
    restart: unless-stopped
    container_name: influxdb
    image: influxdb:1.8.2-alpine
    networks:
      - influxdbnetwork
    volumes:
      #- ./influxdb/etc:/etc/influxdb
      - influxdb-lib:/var/lib/influxdb
    environment:
      - INFLUXDB_ADMIN_USER=root
      - INFLUXDB_ADMIN_PASSWORD=myrootpassword
      - INFLUXDB_DB=bflogger
      - INFLUXDB_MONITOR_STORE_ENABLED=false
    ports:
      - 8083:8083
      - 8086:8086
      - 8088:8088
    privileged: true

networks:
  influxdbnetwork:
volumes:
  influxdb-lib:
    external: false
